MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040

PLATFORM = RP2040

# Lighting and Vial
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
USB_DRIVER = vial
VIA_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes
